#!/usr/bin/env bash
set -euo pipefail

function assert_exist {
    if ! command -v "$1" >/dev/null; then
        >&2 printf "This script needs \"%s\" to work!\n" "$1"
        exit 2
    fi
}

function assert_can_write {
    if [ ! -w "$1" ]; then
        >&2 printf "Current user cannot write into dir \"%s\".\nEither run with sudo, or override BIN_DIR to a user-writable dir.\n" "$1"
        exit 3
    fi
}

function print_usage {
    >&2 printf "Usage: %s (0.11|0.12)\nChoose either between Terraform version v0.11 or v0.12\n" "$(basename "$0")"
}

# Main
BIN_DIR=${BIN_DIR:-/usr/local/bin}
assert_can_write "${BIN_DIR}"

assert_exist curl
assert_exist unzip

# Check for arg count
if [ "$#" -ne 1 ]; then
    print_usage
    exit 1
fi

# Check for first arg validity
if [ "$1" = "0.11" ]; then
    TF_VERSION=0.11.14
    TG_VERSION=0.18.7
elif [ "$1" = "0.12" ]; then
    TF_VERSION=0.12.24
    TG_VERSION=0.22.5
else
    print_usage
    exit 1
fi

# Get OS
if [[ "${OSTYPE}" == "linux-gnu" ]]; then
    OS=linux
elif [[ "${OSTYPE}" == "darwin"* ]]; then
    OS=darwin
elif [[ "${OSTYPE}" == "cygwin" ]] || [[ "${OSTYPE}" == "msys" ]] || [[ "${OSTYPE}" == "win32" ]]; then
    OS=windows
else
    >&2 echo "Invalid OSTYPE ${OSTYPE}, aborting!"
    exit 1
fi

# Get ARCH
RAW_ARCH="$(uname -m)"
if [[ "${RAW_ARCH}" == "x86_64" ]]; then
    ARCH=amd64
elif [[ "${RAW_ARCH}" == "i*86" ]]; then
    ARCH=386
else
    >&2 echo "Invalid ARCH ${RAW_ARCH}, aborting!"
    exit 1
fi

# Terraform
if ! command -v terraform_${TF_VERSION} >/dev/null; then
    curl -LO https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_${OS}_${ARCH}.zip
    unzip terraform_${TF_VERSION}_${OS}_${ARCH}.zip
    mv terraform "${BIN_DIR}/terraform_${TF_VERSION}"
    rm terraform_${TF_VERSION}_${OS}_${ARCH}.zip
fi
cp "$(command -v terraform_${TF_VERSION})" "${BIN_DIR}/terraform"

# Terragrunt
if ! command -v terragrunt_${TG_VERSION} >/dev/null; then
    curl -LO https://github.com/gruntwork-io/terragrunt/releases/download/v${TG_VERSION}/terragrunt_${OS}_${ARCH}
    chmod +x terragrunt_${OS}_${ARCH}
    mv terragrunt_${OS}_${ARCH} "${BIN_DIR}/terragrunt_${TG_VERSION}"
fi
cp "$(command -v terragrunt_${TG_VERSION})" "${BIN_DIR}/terragrunt"

echo "Switched to terraform v${TF_VERSION} and terragrunt v${TG_VERSION}!"
